"""
This type stub file was generated by pyright.
"""

"""
Core functions handling connection and objects base
"""
PANEL_URL = ...
ALIVE_TIMEOUT = ...
def check_premiere_is_alive(crash=...): # -> bool:
    """
    Check if premiere is running and if the pymiere CEP panel is active

    :param crash: (bool) what to do if premiere is not connected
    :return: (bool) is premiere ready to receive instruction from python
    """
    ...

def get_premiere_version():
    """
    Query or get from cache the version of the currently running Premiere pro

    :return: (StrictVersion) version object of current premiere pro
    """
    ...

def eval_script(code=..., filepath=..., decode_json=...): # -> str | Any | dict[Any, Any]:
    """
    Send some ExtendScript code to premiere and wait for the returning value

    :param code: (str) plain text ExtendScript code
    :param filepath: (str) path to a jsx file to execute
    :param decode_json: (bool) decode response using json if possible
    :return: (any) depend on the returned value
    """
    ...

class ExtendScriptError(Exception):
    """
    Exception used to handle error object coming from a try statement in ES
    """
    def __init__(self, error_obj) -> None:
        ...
    


class PymiereBaseObject:
    """
    base object for every mirror object from ES
    """
    def __init__(self, pymiere_id) -> None:
        """
        Init pymiere connection global

        :param pymiere_id: (str) Id of the object we are about to create in extend script, every object is stored in
        $._pymiere var to be accessed easily from python
        """
        ...
    
    def __del__(self): # -> None:
        """
        Delete the reference to this Python object in the ExtendScript side to avoid memory leak (stored in $._pymiere)
        This method is automatically called when our object is garbage collected
        """
        ...
    


class PymiereBaseCollection(PymiereBaseObject):
    def __init__(self, pymiere_id, len_property) -> None:
        """
        These is the base class for all collections, interfacing between premiere Collection objects and python builtin
        iteration tools

        :param pymiere_id: (str) Id of the object we are about to create in extend script, every object is stored in
        $._pymiere var to be accessed easily from python
        :param len_property: (str) name of the property, on the ExtendScript collection object, holding the number of items
        """
        ...
    
    def __getitem__(self, index): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Builtin method for getting the value at the specific index, redirect to ExtendScript similar query

        :param index: (int) index of item we are searching in the collection
        :return: (dict) dict of kwargs to create the object. The object creation itself append in the subclass for
        code inspection/autocomplete purposes
        """
        ...
    
    def __len__(self): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Builtin method for length, we ask premiere using the 'num...' property of the object

        :return: (int) length of the collection
        """
        ...
    
    def __iter__(self): # -> Generator[dict[str, Any] | str | Any | dict[Any, Any] | None, Any, None]:
        """
        Builtin method for iteration, we return our custom iterator to redirect to the __getitem__ method
        This is actually overriden on all super class using a list to keep code type hint in IDE

        :return: (generator)
        """
        ...
    
    def __getattr__(self, item): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Catch property call on this object, we use it to return collection length via len property
        """
        ...
    


class PymiereGenericObject(PymiereBaseObject):
    """
    For all extend scrip objects that are not a specific class, works like the others but does not support code completion
    """
    def __init__(self, pymiere_id, *args, **kwargs) -> None:
        ...
    
    def __setattr__(self, key, value): # -> None:
        """
        Cqlled when we set a property value

        :param key: (str) name of the property
        :param value: (any) new value for the property
        """
        ...
    
    def __getattr__(self, item): # -> Any | PymiereBaseObject | PymiereGenericObject | dict[Any, Any] | Callable[..., PymiereBaseObject | PymiereGenericObject | Any | dict[Any, Any]]:
        """
        Called when we query a prop or execute a function : search in ES if func or prop + return value or function

        :param item: (str) name of function or the property
        :return: (any or func) value of the property or function to be executed
        """
        ...
    
    def inspect(self): # -> None:
        """
        Print functions and properties available on this object, can't be autocompleted
        """
        ...
    


class Array(PymiereBaseCollection):
    """
    Mirror Extend script Array (may be builtin javascript)
    """
    def __init__(self, pymiere_id) -> None:
        ...
    
    def __getitem__(self, index): # -> PymiereBaseObject | PymiereGenericObject | dict[Any, Any]:
        ...
    
    def __setitem__(self, key, value): # -> None:
        ...
    
    def append(self, item): # -> None:
        ...
    
    def push(self, item): # -> None:
        ...
    
    @staticmethod
    def python_list_to_es_declaration(python_list): # -> LiteralString:
        """
        Convert python list to javascript declaration code for the equivalent Array

        :param python_list: (list)
        :return: (str) ExtendScript code
        """
        ...
    
    @classmethod
    def from_python_list(cls, python_list): # -> Self:
        """
        Create an Array in ExtendScript from a python list and return the Array object

        :param python_list: (list)
        :return: (Array)
        """
        ...
    


