"""
This type stub file was generated by pyright.
"""

import platform

"""
Suite of function used to manipulate Premiere Pro app (is it running ? start it...)
Tested on Windows 10 and macOS Catalinq
Should work fine but no guaranty is provided...
"""
if platform.system().lower() == "windows":
    WINDOWS_SYSTEM = ...
else:
    WINDOWS_SYSTEM = ...
CREATE_NO_WINDOW = ...
PREMIERE_PROCESS_NAME = ...
CEPPANEL_PROCESS_NAME = ...
def is_premiere_running(): # -> tuple[Literal[False], None] | tuple[Literal[True], int | Any]:
    """
    Is there a running instance of the Premiere Pro app on this machine ?

    :return: (bool) process is running, (int) pid
    """
    ...

def start_premiere(use_bat=...): # -> int | None:
    """
    Start Premiere pro if not already started

    :param use_bat: (bool) start Premiere Pro using a bat file to keep it running after script exit (in specific cases, windows only)
    :return (int) pid of Premiere process
    """
    ...

def exe_is_running(exe_name): # -> tuple[Literal[False], None] | tuple[Literal[True], int | Any]:
    """
    List processes by name to know if one is running

    :param exe_name: (str) exact name of the process (ex : 'pycharm64.exe' for windows or 'Safari' for mac)
    :return: (bool) process is running, (int) pid
    """
    ...

def count_running_exe(exe_name): # -> int:
    """
    List processes by name to know how many are running

    :param exe_name: (str) exact name of the process (ex : 'pycharm64.exe' for windows or 'Safari' for mac)
    :return: (int) Number of process with given name running
    """
    ...

def get_last_premiere_exe(): # -> str:
    """
    Get the executable path on disk of the last installed Premiere Pro version

    :return: (str) path to executable
    """
    ...

if __name__ == "__main__":
    ...
