"""
This type stub file was generated by pyright.
"""

"""
Generic utils functions
"""
TYPE_CORRESPONDENCE = ...
def write_json_file(filepath, data): # -> None:
    ...

def read_json_file(filepath): # -> Any:
    ...

class MyStr(str):
    """Subclass of string to add code line quicker"""
    def add_line(self, content, indent=...): # -> MyStr:
        ...
    
    def add_empty_line(self, number=...): # -> MyStr:
        ...
    


