"""
This type stub file was generated by pyright.
"""

"""
Collection of higher level functions using low level pymiere code
"""
TICKS_PER_SECONDS = ...
def check_active_sequence(crash=...): # -> tuple[Literal[False], Literal[False]] | tuple[Literal[True], Literal[False]] | tuple[Literal[True], Literal[True]]:
    """
    Check if a project is opened and if a sequence is active

    :param crash: (bool) crash or return status as bool
    :return: (bool), (bool) project is opened, sequence is active
    """
    ...

def get_item_recursive(item, add_root=..., filter_function=...): # -> list[Any]:
    """
    Recursively browse the project items returning a list of item with associated filepaths

    :param item: (ProjectItem) start item to browse from
    :param add_root: (bool) add the root (first given item) to the list and to the path
    :param filter_function: (None or func) function applied on all item, should return a bool adding or dismissing it
    :return: (list of ProjectItem)
    """
    ...

def list_sequences(): # -> SequenceCollection | None:
    """
    List available sequences in the opened project, print infos and return objects

    :return: (list of Sequence) all sequences available in the project
    """
    ...

def list_video(sequence): # -> list[Any]:
    """
    List all video clips on all tracks on this sequence

    :param sequence: (Sequence)
    :return: (list of Clip)
    """
    ...

def edit_clip(clip, start_on_timeline, end_on_timeline, in_point_on_clip, out_point_on_clip, fps=...): # -> None:
    """
    Trim or move clip. This in not available in ppro 2017, use insertClip or overwriteClip

    :param clip: (Clip)
    :param start_on_timeline: (int) Frame at which the clip should start in the sequence timeline
    :param end_on_timeline: (int) Frame at which the clip should end in the sequence timeline
    :param in_point_on_clip: (int) First frame we will see of the clip (in the clip own timeline)
    :param out_point_on_clip: (int) Last frame we will see of the clip (in the clip own timeline)
    """
    ...

def move_clip(clip, seconds): # -> None:
    """
    Move a clip by the number of seconds. Negative values will move the clip left (before the original position),
    positive values move the clip right (after the original position)
    :param clip: (Clip) clip object we want to move
    :param seconds: (float) how many seconds we want to move the clip by, negative value will move left, positive right
    """
    ...

def animate_effect_using_function(clip, effect_name, property_name, anim_func, overwrite=..., keyframe_per_seconds=...): # -> None:
    """
    Reproduce the animation of the given function on an effect property
    :param clip: (Clip) clip object on which we want to change animate the effect
    :param effect_name: (str) name of the effect (ex: 'twirl')
    :param property_name: (str) name of the property on the effect (ex: 'angle')
    :param anim_func: (function) function that take a float number as input (seconds) and return the value for the effect at this time as float
    (ex: lambda s: math.cos(s*2)*10 for a sine wave, lambda s: int(s % 2)*10 for a blinking effect, ...)
    :param overwrite: (bool) if True, clear existing keys else only add keys
    :param keyframe_per_seconds: (float) number of keyframes to place each seconds
    """
    ...

def time_from_seconds(seconds): # -> Time:
    """
    Many properties need a Time object to represent time, this is an helper to create one
    :param seconds: (float) time in seconds
    :return: (pymiere.Time) preseted time object
    """
    ...

def timecode_from_time(time, sequence):
    """
    Some QE methods like move or razor need a timecode in order to work, this convert Time object to timecode

    :param time: (pymiere.Time) time object to be converted
    :param sequence: (pymiere.Sequence) the sequence in which the timecode wil be used to ensure proper formatting
    :return: (str) formated timecode
    """
    ...

def timecode_from_seconds(seconds, sequence): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
    """
    Some QE methods like move or razor need a timecode in order to work, this convert seconds to timecode

    :param seconds: (float or int) seconds to be converted to timecode
    :param sequence: (pymiere.Sequence) the sequence in which the timecode wil be used to ensure proper formatting
    :return: (str) formated timecode
    """
    ...

def get_system_sequence_presets(category=..., resolution=..., preset_name=...):
    """
    To create a new sequence via qe.project.newSequence we need to give a sequence preset file (.sqpreset)
    Base presets come installed with premiere. Select one according to your footage.
    Paths examples : (versions may vary)
        on win: C:\Program Files\Adobe\Adobe Premiere Pro 2020\Settings\SequencePresets
        on mac: /Applications/Adobe Premiere Pro CC 2019/Adobe Premiere Pro CC 2019.app/Contents/Settings/SequencePresets
    :param category: (str) category of the sequence preset in SequencePresets folder (AVCHD, RED R3D, ProRes RAW...)
    :param resolution: (str) category subfolder for sequence resolution
    :param preset_name: (str) actual filename of the sqpreset file (with or without extension)
    :return: (str) path of a sqpreset file
    """
    ...

def has_media_encoder(): # -> bool:
    """
    Check if there is a Media Encoder (AME) version installed that work with the currently running Premiere Pro

    :return: (bool) True if suitable AME version found
    """
    ...

def clone_sequence(sequence, new_sequence_name=...): # -> Sequence:
    """
    Equivalent of Sequence.clone() with return value and optional rename
    :param sequence: (Sequence) sequence object to duplicate
    :param new_sequence_name: (str or None) optional new name for the duplicated sequence
    :return: (Sequence) duplicated sequence object
    """
    ...

def add_video_track(): # -> None:
    """ Adds a new empty video track above all the others """
    ...

def add_audio_track(): # -> None:
    """ Adds a new empty audio track above all the others """
    ...

if __name__ == "__main__":
    ...
