"""
This type stub file was generated by pyright.
"""

from pymiere.objects.premiere_objects import *

class StartVars:
    def __init__(self) -> None:
        ...
    
    @property
    def NaN(self): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        ...
    
    @NaN.setter
    def NaN(self, NaN): # -> None:
        ...
    
    @property
    def Infinity(self): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        ...
    
    @Infinity.setter
    def Infinity(self, Infinity): # -> None:
        ...
    
    @property
    def undefined(self): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        ...
    
    @undefined.setter
    def undefined(self, undefined): # -> None:
        ...
    
    @property
    def qe(self): # -> PymiereBaseObject | PymiereGenericObject | dict[Any, Any]:
        ...
    
    @qe.setter
    def qe(self, qe):
        ...
    
    @property
    def app(self): # -> Application:
        ...
    
    @app.setter
    def app(self, app):
        ...
    
    @property
    def apps(self): # -> Array:
        ...
    
    @apps.setter
    def apps(self, apps):
        ...
    
    @property
    def document(self): # -> Document:
        ...
    
    @document.setter
    def document(self, document):
        ...
    
    @property
    def ProjectItemType(self): # -> ProjectItemType:
        ...
    
    @ProjectItemType.setter
    def ProjectItemType(self, ProjectItemType):
        ...
    
    @property
    def ScratchDiskType(self): # -> ScratchDiskType:
        ...
    
    @ScratchDiskType.setter
    def ScratchDiskType(self, ScratchDiskType):
        ...
    
    @property
    def RegisteredDirectories(self): # -> RegisteredDirectories:
        ...
    
    @RegisteredDirectories.setter
    def RegisteredDirectories(self, RegisteredDirectories):
        ...
    
    @property
    def UtilityFunctions(self): # -> UtilityFunctions:
        ...
    
    @UtilityFunctions.setter
    def UtilityFunctions(self, UtilityFunctions):
        ...
    
    @property
    def Dollar(self): # -> Dollar:
        ...
    
    @Dollar.setter
    def Dollar(self, Dollar):
        ...
    
    @property
    def Math(self): # -> Math:
        ...
    
    @Math.setter
    def Math(self, Math):
        ...
    
    @property
    def premierepro13(self): # -> PymiereBaseObject | PymiereGenericObject | dict[Any, Any]:
        ...
    
    @premierepro13.setter
    def premierepro13(self, premierepro13): # -> None:
        ...
    
    @property
    def AEFTBridge(self): # -> PymiereBaseObject | PymiereGenericObject | dict[Any, Any]:
        ...
    
    @AEFTBridge.setter
    def AEFTBridge(self, AEFTBridge): # -> None:
        ...
    
    @property
    def PHXSBridge(self): # -> PymiereBaseObject | PymiereGenericObject | dict[Any, Any]:
        ...
    
    @PHXSBridge.setter
    def PHXSBridge(self, PHXSBridge): # -> None:
        ...
    
    @property
    def CCXHostBridge(self): # -> PymiereBaseObject | PymiereGenericObject | dict[Any, Any]:
        ...
    
    @CCXHostBridge.setter
    def CCXHostBridge(self, CCXHostBridge): # -> None:
        ...
    
    @property
    def f(self): # -> File:
        ...
    
    @f.setter
    def f(self, f): # -> None:
        ...
    
    @property
    def JSON(self): # -> PymiereBaseObject | PymiereGenericObject | dict[Any, Any]:
        ...
    
    @JSON.setter
    def JSON(self, JSON): # -> None:
        ...
    
    def encodeURI(self, text): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Encodes a string after RFC2396. Create an UTF-8 ASCII encoded version of this string. The string is converted into UTF-8. Every non-alphanumeric character is encoded as a percent escape character of the form %xx, where xx is the hex value of the character. After the conversion to UTF-8 encoding and escaping, it is guaranteed that the string does not contain characters codes greater than 127. The list of characters not to be encoded is -_.!~'();/?:@&=+Dollar,#. The method returns false on errors. 
        :param text: The text to encode.
        :type text: str
        """
        ...
    
    def encodeURIComponent(self, text): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Encodes a string after RFC2396. Create an UTF-8 ASCII encoded version of this string. The string is converted into UTF-8. Every non-alphanumeric character is encoded as a percent escape character of the form %xx, where xx is the hex value of the character. After the conversion to UTF-8 encoding and escaping, it is guaranteed that the string does not contain characters codes greater than 127. The list of characters not to be encoded is -_.!~'(). The method returns false on errors. 
        :param text: The text to encode.
        :type text: str
        """
        ...
    
    def decodeURI(self, uri): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Decodes a string created with encodeURI(). 
        :param uri: The text to decode.
        :type uri: str
        """
        ...
    
    def decodeURIComponent(self, uri): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Decodes a string created with encodeURIComponent(). 
        :param uri: The text to decode.
        :type uri: str
        """
        ...
    
    def escape(self, text): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Creates a URL-encoded string from aString. In the new string, characters of aString that require URL encoding are replaced with the format %xx, where xx is the hexadecimal value of the character code in the Unicode character set.This format is used to transmit information appended to a URL during, for example, execution of the GET method.Use the unescape() global function to translate the string back into its original format. Returns a string which is aString URL-encoded. 
        :param aString: The string to be encoded.
        :type text: str
        """
        ...
    
    def eval(self, source): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Evaluates its argument as a JavaScript script, and returns the result of evaluation. You can pass the result of an object's toSource() method to reconstruct that object. 
        :param stringExpression: The string to evaluate.
        :type source: str
        """
        ...
    
    def uneval(self, what): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Creates a source code representation of the supplied argument, and returns it as a string. 
        :param what: The object to uneval.
        :type what: any
        """
        ...
    
    def isFinite(self, what): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Evaluates an expression and reports whether the result is a finite number. Returns true if the expression is a finite number, false otherwise. False if the value is infinity or negative infinity. 
        :param expression: Any valid JavaScript expression.
        :type what: float
        """
        ...
    
    def isNaN(self, what): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Evaluates an expression and reports whether the result is "Not-a-Number" (NaN). Returns true if the result of evaluation is not a number (NaN), false if the value is a number. 
        :param expression: Any valid JavaScript expression.
        :type what: float
        """
        ...
    
    def parseInt(self, text, base): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Extracts an integer from a string. Parses a string to find the first set of characters, in a specified base, that can be converted to an integer, and returns that integer, or NaN if it does not encounter characters that it can convert to a number. 
        :param text: The string from which to extract an integer.
        :param base: The base of the string to parse (from base 2 to base 36). If not supplied, base is determined by the format of string.
        :type text: str
        :type base: float
        """
        ...
    
    def parseFloat(self, txt): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Extracts a floating-point number from a string. Parses a string to find the first set of characters that can be converted to a floating point number, and returns that number, or NaN if it does not encounter characters that it can converted to a number.The function supports exponential notation. 
        :param text: The string from which to extract a floating point number.
        :type txt: str
        """
        ...
    
    def unescape(self, uri): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Translates URL-encoded string into a regular string, and returns that string. Use the escape() global function to URL-encode strings. 
        :param stringExpression: The URL-encoded string to convert.
        :type uri: str
        """
        ...
    
    def localize(self, what): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Localizes a ZString-encoded string and merges additional arguments into the string. 
        :param what: The string to localize. A ZString-encoded string that can contain placeholder for additional arguments in the form %1 to %n.
        :param arguments: Optional argument(s) to be merged into the string. There may be more than one argument.
        :type what: any
        """
        ...
    
    def isXMLName(self, name): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Returns true if the supplied string is a valid XML name. 
        :param name: The XML name to test.
        :type name: str
        """
        ...
    
    def setDefaultXMLNamespace(self, ns): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Defines the default XML namespace. This is a replacement function for the standard JavaScript statement set default xml namespace. 
        :param namespace: The namespace to use. Omit this parameter to return to the empty namespace. This is either a Namespace object or a string.
        :type ns: Namespace
        """
        ...
    
    def alert(self, prompt): # -> None:
        """
        Displays an alert box 
        :param message: The text to display
        :param title: The title of the alert; ignored on the Macintosh
        :param errorIcon: Display an Error icon; ignored on the Macintosh
        :type prompt: str
        """
        ...
    
    def confirm(self, prompt): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Displays an alert box with Yes and No buttons; returns true for Yes 
        :param message: The text to display
        :param noAsDefault: Set to true to set the No button as the default button
        :param title: The title of the alert; ignored on the Macintosh
        :type prompt: str
        """
        ...
    
    def prompt(self, prompt): # -> dict[str, Any] | str | Any | dict[Any, Any] | None:
        """
        Displays a dialog allowing the user to enter text Returns null if the user cancelled the dialog, the text otherwise 
        :param prompt: The text to display
        :param default_: The default text to preset the edit field with
        :param title: The title of the dialog;
        :type prompt: str
        """
        ...
    


