"""
This type stub file was generated by pyright.
"""

from importlib import metadata
from osrparse.utils import GameMode, Key, KeyMania, KeyTaiko, LifeBarState, Mod, ReplayEvent, ReplayEventCatch, ReplayEventMania, ReplayEventOsu, ReplayEventTaiko
from osrparse.replay import Replay, parse_replay_data

__version__ = ...
__all__ = ["GameMode", "Mod", "Replay", "ReplayEvent", "Key", "ReplayEventOsu", "ReplayEventTaiko", "ReplayEventMania", "ReplayEventCatch", "KeyTaiko", "KeyMania", "parse_replay_data", "LifeBarState"]
