"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from typing import List, Optional
from dataclasses import dataclass
from osrparse.utils import GameMode, LifeBarState, Mod, ReplayEvent

class _Unpacker:
    """
    Helper class for dealing with the ``.osr`` format. Not intended to be used
    by consumers.
    """
    def __init__(self, replay_data) -> None:
        ...
    
    def unpack_byte(self): # -> Any:
        ...
    
    def unpack_short(self): # -> Any:
        ...
    
    def unpack_int(self):
        ...
    
    def unpack_long(self): # -> Any:
        ...
    
    def unpack_once(self, specifier): # -> Any:
        ...
    
    def string_length(self, binarystream):
        ...
    
    def unpack_string(self): # -> None:
        ...
    
    def unpack_timestamp(self): # -> datetime:
        ...
    
    def unpack_play_data(self, mode): # -> tuple[list[Any], int | None]:
        ...
    
    @staticmethod
    def parse_replay_data(replay_data_str, mode): # -> tuple[list[Any], int | None]:
        ...
    
    def unpack_replay_id(self): # -> Any:
        ...
    
    def unpack_life_bar(self): # -> list[LifeBarState] | None:
        ...
    
    def unpack(self): # -> Replay:
        ...
    


class _Packer:
    def __init__(self, replay, *, dict_size=..., mode=...) -> None:
        ...
    
    def pack_byte(self, data): # -> bytes:
        ...
    
    def pack_short(self, data): # -> bytes:
        ...
    
    def pack_int(self, data): # -> bytes:
        ...
    
    def pack_long(self, data): # -> bytes:
        ...
    
    def pack_ULEB128(self, data): # -> bytes:
        ...
    
    def pack_string(self, data): # -> bytes:
        ...
    
    def pack_timestamp(self): # -> bytes:
        ...
    
    def pack_life_bar(self): # -> bytes:
        ...
    
    def pack_replay_data(self): # -> bytes:
        ...
    
    def pack(self): # -> bytes:
        ...
    


@dataclass
class Replay:
    """
    A replay found in a ``.osr`` file, or following the osr format. To create a
    replay, you likely want ``Replay.from_path``, ``Replay.from_file``, or
    ``Replay.from_string``.

    Attributes
    ----------
    mode: GameMode
        The game mode this replay was played on.
    game_version: int
        The game version this replay was played on.
    beatmap_hash: str
        The hash of the beatmap this replay was played on.
    username: str
        The user that played this replay.
    replay_hash:
        The hash of this replay.
    count_300: int
        The number of 300 judgments in this replay.
    count_100: int
        The number of 100 judgments in this replay.
    count_50: int
        The number of 50 judgments in this replay.
    count_geki: int
        The number of geki judgments in this replay.
    count_katu: int
        The number of katu judgments in this replay.
    count_miss: int
        The number of misses in this replay.
    score: int
        The score of this replay.
    max_combo: int
        The maximum combo attained in this replay.
    perfect: bool
        Whether this replay was perfect or not.
    mods: Mod
        The mods this replay was played with.
    life_bar_graph: Optional[List[LifeBarState]]
        The life bar of this replay over time.
    replay_data: List[ReplayEvent]
        The replay data of the replay, including cursor position and keys
        pressed.
    replay_id: int
        The replay id of this replay, or 0 if not submitted.
    rng_seed: Optional[int]
        The rng seed of this replay, or ``None`` if not present (typically not
        present on older replays).
    """
    mode: GameMode
    game_version: int
    beatmap_hash: str
    username: str
    replay_hash: str
    count_300: int
    count_100: int
    count_50: int
    count_geki: int
    count_katu: int
    count_miss: int
    score: int
    max_combo: int
    perfect: bool
    mods: Mod
    life_bar_graph: Optional[List[LifeBarState]]
    timestamp: datetime
    replay_data: List[ReplayEvent]
    replay_id: int
    rng_seed: Optional[int]
    @staticmethod
    def from_path(path): # -> Replay:
        """
        Creates a new ``Replay`` object from the ``.osr`` file at the given
        ``path``.

        Parameters
        ----------
        path: str or os.PathLike
            The path to the osr file to read from.

        Returns
        -------
        Replay
            The parsed replay object.
        """
        ...
    
    @staticmethod
    def from_file(file): # -> Replay:
        """
        Creates a new ``Replay`` object from an open file object.

        Parameters
        ----------
        file: file-like
           The file object to read from.

        Returns
        -------
        Replay
            The parsed replay object.
        """
        ...
    
    @staticmethod
    def from_string(data): # -> Replay:
        """
        Creates a new ``Replay`` object from a string containing ``.osr`` data.

        Parameters
        ----------
        data: str
           The data to parse.

        Returns
        -------
        Replay
            The parsed replay object.
        """
        ...
    
    def write_path(self, path, *, dict_size=..., mode=...): # -> None:
        """
        Writes the replay to the given ``path``.

        Parameters
        ----------
        path: str or os.PathLike
           The path to where to write the replay.

        Notes
        -----
        This uses the current values of any attributes, and so can be used to
        create an edited version of a replay, by first reading a replay, editing
        an attribute, then writing the replay back to its file.
        """
        ...
    
    def write_file(self, file, *, dict_size=..., mode=...): # -> None:
        """
        Writes the replay to an open file object.

        Parameters
        ----------
        file: file-like
           The file object to write to.
        """
        ...
    
    def pack(self, *, dict_size=..., mode=...): # -> bytes:
        """
        Returns the text representing this ``Replay``, in ``.osr`` format.
        The text returned by this method is suitable for writing to a file as a
        valid ``.osr`` file.

        Returns
        -------
        str
            The text representing this ``Replay``, in ``.osr`` format.
        """
        ...
    


def parse_replay_data(data_string, *, decoded=..., decompressed=..., mode=...) -> List[ReplayEvent]:
    """
    Parses the replay data portion of a replay from a string. This method is
    siutable for use with the replay data returned by api v1's ``/get_replay``
    endpoint, for instance.

    Parameters
    ----------
    data_string: str or bytes
        The replay data to parse.
    decoded: bool
        Whether ``data_string`` has already been decoded from a b64
        representation. Api v1 returns a base 64 encoded string, for instance.
    decompressed: bool
        Whether ``data_string`` has already been both decompressed from lzma,
        and decoded to ascii.
        |br|
        For instance, the following two calls are equivalent:
        ```
        >>> parse_replay_data(lzma_string, decoded=True)
        >>> ...
        >>> lzma_string = lzma.decompress(lzma_string).decode("ascii")
        >>> parse_replay_data(lzma_string, decompressed=True)
        ```
        |br|
        If ``decompressed`` is ``True``, ``decoded`` is automatically set to
        ``True`` as well (ie, if ``decompressed`` is ``True``, we will assume
        ``data_string`` is not base 64 encoded).
    mode: GameMode
        What mode to parse the replay data as.
    """
    ...

